#!/usr/bin/env bash

sigterm() {
    pkill -P $$
    exit 0
}

trap sigterm 15

export LC_ALL=C.UTF-8 

get_status() {
    connected_device=
    while read -r device; do
        if [[ $device != lo* && $device == *:activated ]]; then
            connected_device=$(cut -d: -f1 - <<< "$device")
            break
        fi
    done < <(nmcli -g device,state con show --order active:type)
    if [[ -z $connected_device ]]; then
        if [[ $(nmcli -g general.state dev show wlp1s0) == 30* ]]; then
            echo '{"icon": "󰖪", "connection": "disconnected"}'
        else
            echo '{"icon": "󰲛", "connection": "disconnected"}'
        fi
        return 0
    fi
    case $(nmcli -g general.type dev show "$connected_device") in
        wifi) echo "{\"icon\": \"󰖩\", \"connection\": \"$(nmcli -g general.connection dev show "$connected_device")\"}" ;;
        *) echo "{\"icon\": \"󰛳\", \"connection\": \"$(nmcli -g general.connection dev show "$connected_device")\"}" ;;
    esac
}

get_status
while read -r event; do
    if [[ $event == *primary* ]]; then
        get_status
    fi
done < <(nmcli monitor)
