#!/usr/bin/env bash
fields=(
    '@@@status@@@:@@@{{lc(status)}}@@@'
    '@@@player@@@:@@@{{playerName}}@@@'
    '@@@artist@@@:@@@{{artist}}@@@'
    '@@@title@@@:@@@{{title}}@@@'
)
IFS=',' arg="{${fields[*]}}"
exec playerctl metadata -aFf "$arg" | while read -r output; do
    escaped=${output//\"/\\\"}
    echo "${escaped//@@@/\"}"
done
