#!/usr/bin/env bash

export LC_ALL=C 

get_status() {
    if [[ $(nmcli -g general.state dev show wlp1s0) == 30* ]]; then
        echo '{"icon": "󰖪", "connection": "disconnected"}'
    else
        echo '{"icon": "󰖩", "connection": "'"$(nmcli -g general.connection dev show wlp1s0)\"}"
    fi
}

get_status
while read -r event; do
    if [[ $event == *connected ]]; then
        get_status
    fi
done < <(nmcli device monitor wlp1s0)
